const stockSeeds = [
  {
    ticker: "META",
    name: "Meta Platforms, Inc. Class A Common Stock",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0001326801",
    composite_figi: "BBG000MM2P62",
    share_class_figi: "BBG001SQCQC5",
    last_updated_utc: "2024-04-26T00:00:00Z",
  },
  {
    ticker: "CLRMF",
    name: "CLEAN AIR METALS INC",
    market: "otc",
    locale: "us",
    type: "OS",
    active: true,
    currency_name: "USD",
    composite_figi: "BBG00V31GJG9",
    share_class_figi: "BBG001SF1XH1",
    last_updated_utc: "2023-10-11T21:28:33.159Z",
  },
  {
    ticker: "MTA",
    name: "Metalla Royalty & Streaming Ltd.",
    market: "stocks",
    locale: "us",
    primary_exchange: "XASE",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0001722606",
    composite_figi: "BBG000HM5YW7",
    share_class_figi: "BBG001SF89W0",
    last_updated_utc: "2024-04-26T00:00:00Z",
  },
  {
    ticker: "NDENF",
    name: "AFRICAN ENERGY METALS INC",
    market: "otc",
    locale: "us",
    type: "OS",
    active: true,
    currency_name: "USD",
    composite_figi: "BBG003347CM3",
    share_class_figi: "BBG001S8FS29",
    last_updated_utc: "2024-04-10T08:45:14.641Z",
  },
  {
    ticker: "ICOP",
    name: "iShares Copper and Metals Mining ETF",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "ETF",
    active: true,
    currency_name: "usd",
    cik: "0001100663",
    composite_figi: "BBG01H2QR9F6",
    share_class_figi: "BBG01H2QRB89",
    last_updated_utc: "2024-04-26T00:00:00Z",
  },
  {
    ticker: "GBCHF",
    name: "METAVERSE CAP CORP",
    market: "otc",
    locale: "us",
    type: "OS",
    active: true,
    currency_name: "USD",
    composite_figi: "BBG00LK6SSW0",
    share_class_figi: "BBG00JXGPZK9",
    last_updated_utc: "2021-12-08T09:45:19.34Z",
  },
  {
    ticker: "AMGY",
    name: "AMERICAN METAL&TECH INC",
    market: "otc",
    locale: "us",
    type: "CS",
    active: true,
    currency_name: "USD",
    composite_figi: "BBG000BQNX29",
    share_class_figi: "BBG001S6XCK8",
    last_updated_utc: "2023-10-11T21:27:48.859Z",
  },
  {
    ticker: "I:NQUSB55102015T",
    name: "Nasdaq US Benchmark Metal Fabricating TR Index",
    market: "indices",
    locale: "us",
    active: true,
    source_feed: "NasdaqGIDS",
  },
  {
    ticker: "CYPMF",
    name: "CYPRIUM METALS LTD",
    market: "otc",
    locale: "us",
    type: "OS",
    active: true,
    currency_name: "USD",
    last_updated_utc: "2022-04-08T06:50:18.462Z",
  },
  {
    ticker: "MRNJ",
    name: "METATRON INC",
    market: "otc",
    locale: "us",
    type: "CS",
    active: true,
    currency_name: "USD",
    composite_figi: "BBG000BHNQY9",
    share_class_figi: "BBG001SB3X33",
    last_updated_utc: "2022-10-25T05:00:38.897Z",
  },
];

const detailsSeeds = {
  ticker: "AAPL",
  name: "Apple Inc.",
  market: "stocks",
  locale: "us",
  primary_exchange: "XNAS",
  type: "CS",
  active: true,
  currency_name: "usd",
  cik: "0000320193",
  composite_figi: "BBG000B9XRY4",
  share_class_figi: "BBG001S5N8V8",
  market_cap: 2614310453300,
  phone_number: "(408) 996-1010",
  address: {
    address1: "ONE APPLE PARK WAY",
    city: "CUPERTINO",
    state: "CA",
    postal_code: "95014",
  },
  description:
    "Apple is among the largest companies in the world, with a broad portfolio of hardware and software products targeted at consumers and businesses. Apple's iPhone makes up a majority of the firm sales, and Apple's other products like Mac, iPad, and Watch are designed around the iPhone as the focal point of an expansive software ecosystem. Apple has progressively worked to add new applications, like streaming video, subscription bundles, and augmented reality. The firm designs its own software and semiconductors while working with subcontractors like Foxconn and TSMC to build its products and chips. Slightly less than half of Apple's sales come directly through its flagship stores, with a majority of sales coming indirectly through partnerships and distribution.",
  sic_code: "3571",
  sic_description: "ELECTRONIC COMPUTERS",
  ticker_root: "AAPL",
  homepage_url: "https://www.apple.com",
  total_employees: 161000,
  list_date: "1980-12-12",
  branding: {
    logo_url:
      "https://api.polygon.io/v1/reference/company-branding/YXBwbGUuY29t/images/2024-04-01_logo.svg",
    icon_url:
      "https://api.polygon.io/v1/reference/company-branding/YXBwbGUuY29t/images/2024-04-01_icon.jpeg",
  },
  share_class_shares_outstanding: 15441880000,
  weighted_shares_outstanding: 15441881000,
  round_lot: 100,
};

export { stockSeeds, detailsSeeds };
